import type { KeyboardLayout } from "@/types/keyboard";

export const ruJcukenLayout: KeyboardLayout = {
  id: "ru-jcuken",
  name: "Russian (JCUKEN) — mapped from US QWERTY codes",
  rows: [
    [
      { code: "KeyQ", label: "Й", zone: "pinky" },
      { code: "KeyW", label: "Ц", zone: "ring" },
      { code: "KeyE", label: "У", zone: "middle" },
      { code: "KeyR", label: "К", zone: "index" },
      { code: "KeyT", label: "Е", zone: "index" },
      { code: "KeyY", label: "Н", zone: "index" },
      { code: "KeyU", label: "Г", zone: "index" },
      { code: "KeyI", label: "Ш", zone: "middle" },
      { code: "KeyO", label: "Щ", zone: "ring" },
      { code: "KeyP", label: "З", zone: "pinky" },
      { code: "BracketLeft", label: "Х", zone: "pinky" },
      { code: "BracketRight", label: "Ъ", zone: "pinky" },
    ],
    [
      { code: "KeyA", label: "Ф", zone: "pinky" },
      { code: "KeyS", label: "Ы", zone: "ring" },
      { code: "KeyD", label: "В", zone: "middle" },
      { code: "KeyF", label: "А", zone: "index" },
      { code: "KeyG", label: "П", zone: "index" },
      { code: "KeyH", label: "Р", zone: "index" },
      { code: "KeyJ", label: "О", zone: "index" },
      { code: "KeyK", label: "Л", zone: "middle" },
      { code: "KeyL", label: "Д", zone: "ring" },
      { code: "Semicolon", label: "Ж", zone: "pinky" },
      { code: "Quote", label: "Э", zone: "pinky" },
    ],
    [
      { code: "KeyZ", label: "Я", zone: "pinky" },
      { code: "KeyX", label: "Ч", zone: "ring" },
      { code: "KeyC", label: "С", zone: "middle" },
      { code: "KeyV", label: "М", zone: "index" },
      { code: "KeyB", label: "И", zone: "index" },
      { code: "KeyN", label: "Т", zone: "index" },
      { code: "KeyM", label: "Ь", zone: "index" },
      { code: "Comma", label: "Б", zone: "middle" },
      { code: "Period", label: "Ю", zone: "ring" },
      { code: "Slash", label: ".", zone: "pinky" },
    ],
    [{ code: "Space", label: "SPACE", zone: "thumb", width: 64 }],
  ],
  codeToChar: {
    KeyQ: { lower: "й", upper: "Й" },
    KeyW: { lower: "ц", upper: "Ц" },
    KeyE: { lower: "у", upper: "У" },
    KeyR: { lower: "к", upper: "К" },
    KeyT: { lower: "е", upper: "Е" },
    KeyY: { lower: "н", upper: "Н" },
    KeyU: { lower: "г", upper: "Г" },
    KeyI: { lower: "ш", upper: "Ш" },
    KeyO: { lower: "щ", upper: "Щ" },
    KeyP: { lower: "з", upper: "З" },
    BracketLeft: { lower: "х", upper: "Х" },
    BracketRight: { lower: "ъ", upper: "Ъ" },
    KeyA: { lower: "ф", upper: "Ф" },
    KeyS: { lower: "ы", upper: "Ы" },
    KeyD: { lower: "в", upper: "В" },
    KeyF: { lower: "а", upper: "А" },
    KeyG: { lower: "п", upper: "П" },
    KeyH: { lower: "р", upper: "Р" },
    KeyJ: { lower: "о", upper: "О" },
    KeyK: { lower: "л", upper: "Л" },
    KeyL: { lower: "д", upper: "Д" },
    Semicolon: { lower: "ж", upper: "Ж" },
    Quote: { lower: "э", upper: "Э" },
    KeyZ: { lower: "я", upper: "Я" },
    KeyX: { lower: "ч", upper: "Ч" },
    KeyC: { lower: "с", upper: "С" },
    KeyV: { lower: "м", upper: "М" },
    KeyB: { lower: "и", upper: "И" },
    KeyN: { lower: "т", upper: "Т" },
    KeyM: { lower: "ь", upper: "Ь" },
    Comma: { lower: "б", upper: "Б" },
    Period: { lower: "ю", upper: "Ю" },
    Slash: { lower: ".", upper: "," },
    Space: { lower: " ", upper: " " },
  },
};

