import type { KeyboardLayout } from "@/types/keyboard";

export const usQwertyLayout: KeyboardLayout = {
  id: "us-qwerty",
  name: "US (QWERTY) — physical key codes",
  rows: [
    [
      { code: "KeyQ", label: "Q", zone: "pinky" },
      { code: "KeyW", label: "W", zone: "ring" },
      { code: "KeyE", label: "E", zone: "middle" },
      { code: "KeyR", label: "R", zone: "index" },
      { code: "KeyT", label: "T", zone: "index" },
      { code: "KeyY", label: "Y", zone: "index" },
      { code: "KeyU", label: "U", zone: "index" },
      { code: "KeyI", label: "I", zone: "middle" },
      { code: "KeyO", label: "O", zone: "ring" },
      { code: "KeyP", label: "P", zone: "pinky" },
      { code: "BracketLeft", label: "[", zone: "pinky" },
      { code: "BracketRight", label: "]", zone: "pinky" },
      { code: "Backslash", label: "\\", zone: "pinky" },
    ],
    [
      { code: "KeyA", label: "A", zone: "pinky" },
      { code: "KeyS", label: "S", zone: "ring" },
      { code: "KeyD", label: "D", zone: "middle" },
      { code: "KeyF", label: "F", zone: "index" },
      { code: "KeyG", label: "G", zone: "index" },
      { code: "KeyH", label: "H", zone: "index" },
      { code: "KeyJ", label: "J", zone: "index" },
      { code: "KeyK", label: "K", zone: "middle" },
      { code: "KeyL", label: "L", zone: "ring" },
      { code: "Semicolon", label: ";", zone: "pinky" },
      { code: "Quote", label: "'", zone: "pinky" },
    ],
    [
      { code: "KeyZ", label: "Z", zone: "pinky" },
      { code: "KeyX", label: "X", zone: "ring" },
      { code: "KeyC", label: "C", zone: "middle" },
      { code: "KeyV", label: "V", zone: "index" },
      { code: "KeyB", label: "B", zone: "index" },
      { code: "KeyN", label: "N", zone: "index" },
      { code: "KeyM", label: "M", zone: "index" },
      { code: "Comma", label: ",", zone: "middle" },
      { code: "Period", label: ".", zone: "ring" },
      { code: "Slash", label: "/", zone: "pinky" },
    ],
    [{ code: "Space", label: "SPACE", zone: "thumb", width: 64 }],
  ],
  codeToChar: {
    KeyQ: { lower: "q", upper: "Q" },
    KeyW: { lower: "w", upper: "W" },
    KeyE: { lower: "e", upper: "E" },
    KeyR: { lower: "r", upper: "R" },
    KeyT: { lower: "t", upper: "T" },
    KeyY: { lower: "y", upper: "Y" },
    KeyU: { lower: "u", upper: "U" },
    KeyI: { lower: "i", upper: "I" },
    KeyO: { lower: "o", upper: "O" },
    KeyP: { lower: "p", upper: "P" },
    BracketLeft: { lower: "[", upper: "{" },
    BracketRight: { lower: "]", upper: "}" },
    Backslash: { lower: "\\", upper: "|" },

    KeyA: { lower: "a", upper: "A" },
    KeyS: { lower: "s", upper: "S" },
    KeyD: { lower: "d", upper: "D" },
    KeyF: { lower: "f", upper: "F" },
    KeyG: { lower: "g", upper: "G" },
    KeyH: { lower: "h", upper: "H" },
    KeyJ: { lower: "j", upper: "J" },
    KeyK: { lower: "k", upper: "K" },
    KeyL: { lower: "l", upper: "L" },
    Semicolon: { lower: ";", upper: ":" },
    Quote: { lower: "'", upper: "\"" },

    KeyZ: { lower: "z", upper: "Z" },
    KeyX: { lower: "x", upper: "X" },
    KeyC: { lower: "c", upper: "C" },
    KeyV: { lower: "v", upper: "V" },
    KeyB: { lower: "b", upper: "B" },
    KeyN: { lower: "n", upper: "N" },
    KeyM: { lower: "m", upper: "M" },
    Comma: { lower: ",", upper: "<" },
    Period: { lower: ".", upper: ">" },
    Slash: { lower: "/", upper: "?" },
    Space: { lower: " ", upper: " " },
  },
};

